const API_URL='https://script.google.com/macros/s/AKfycbwhAYHg3_Ty4nHvSacjXSS3NEooc2y58m-XHk57zyH9mE03KflQ07A8jYVSPYEP2jK1/exec';
const APP={customers:[],invoices:[],settings:{}};
const $=id=>document.getElementById(id);

document.addEventListener('DOMContentLoaded',()=>{
  $('newInvoiceBtn').onclick=openNewInvoice;$('refreshBtn').onclick=loadData;
  $('searchInput').oninput=filterInvoices;$('addItemBtn').onclick=()=>addItem();
  $('saveBtn').onclick=saveInvoice;$('printBtn').onclick=()=>window.print();
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
  $('customerSelect').onchange=selectCustomer;$('taxPercent').oninput=calculate;
  $('invoiceDate').value=new Date().toISOString().slice(0,10);loadData();
});
async function api(action,payload={}){if(API_URL.includes('PASTE_APPS_SCRIPT'))throw Error('API URL belum diisi di js/app.js');const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})});const d=await r.json();if(d.success===false)throw Error(d.error||'API error');return d}
async function loadData(){try{const d=await api('getInitialData');APP.customers=d.customers||[];APP.invoices=d.invoices||[];APP.settings=d.settings||{};renderCustomers();renderInvoices();renderStats()}catch(e){toast(e.message,true)}}
function renderStats(){let p=APP.invoices.filter(x=>x.status==='Paid').length,u=APP.invoices.filter(x=>['Unpaid','Partially Paid'].includes(x.status)).length;$('stats').innerHTML=`<div class="stat"><b>${APP.invoices.length}</b><span>TOTAL INVOICE</span></div><div class="stat"><b>${p}</b><span>PAID</span></div><div class="stat"><b>${u}</b><span>UNPAID</span></div>`}
function renderCustomers(){$('customerSelect').innerHTML='<option value="">-- Pilih Customer --</option>'+APP.customers.map(c=>`<option value="${escapeHtml(c.id)}">${escapeHtml(c.id)} - ${escapeHtml(c.name)}</option>`).join('')}
function renderInvoices(list=APP.invoices){$('emptyState').hidden=!!list.length;$('invoiceList').innerHTML=list.map(x=>`<tr><td><strong>${escapeHtml(x.invoiceNo)}</strong></td><td>${escapeHtml(x.date)}</td><td>${escapeHtml(x.customer)}</td><td>${money(x.grandTotal)}</td><td><span class="status ${escapeHtml(x.status)}">${escapeHtml(x.status)}</span></td><td><button class="btn btn-light btn-small" onclick="previewInvoice('${encodeURIComponent(x.invoiceNo)}')">View</button></td></tr>`).join('')}
function filterInvoices(){let q=$('searchInput').value.toLowerCase();renderInvoices(APP.invoices.filter(x=>String(x.invoiceNo).toLowerCase().includes(q)||String(x.customer).toLowerCase().includes(q)))}
function openNewInvoice(){$('invoiceNo').value='';$('customerSelect').value='';['customer','phone','email','address','notes'].forEach(id=>$(id).value='');$('status').value='Draft';$('paymentMethod').value='Transfer Bank';$('taxPercent').value=APP.settings['Pajak Default (%)']||15;$('itemsBody').innerHTML='';addItem();openModal('formModal')}
function selectCustomer(){let c=APP.customers.find(x=>x.id===$('customerSelect').value);if(!c)return;[['customer','name'],['phone','phone'],['email','email'],['address','address']].forEach(([a,b])=>$(a).value=c[b]||'')}
function addItem(item={}){let tr=document.createElement('tr');tr.innerHTML=`<td class="item-no"></td><td><input class="description" value="${escapeAttr(item.description||'')}"></td><td><input class="qty" type="number" min="0" value="${item.qty??1}"></td><td><input class="price" type="number" min="0" value="${item.price??0}"></td><td class="item-total">Rp 0</td><td><button class="delete-item">×</button></td>`;tr.querySelectorAll('input').forEach(x=>x.oninput=calculate);tr.querySelector('.delete-item').onclick=()=>{tr.remove();renumber();calculate()};$('itemsBody').appendChild(tr);renumber();calculate()}
function renumber(){document.querySelectorAll('.item-no').forEach((x,i)=>x.textContent=i+1)}
function getItems(){return [...document.querySelectorAll('#itemsBody tr')].map(tr=>({description:tr.querySelector('.description').value.trim(),qty:+tr.querySelector('.qty').value||0,price:+tr.querySelector('.price').value||0})).filter(x=>x.description||x.qty||x.price)}
function calculate(){let s=0;document.querySelectorAll('#itemsBody tr').forEach(tr=>{let q=+tr.querySelector('.qty').value||0,p=+tr.querySelector('.price').value||0,t=q*p;s+=t;tr.querySelector('.item-total').textContent=money(t)});let tax=s*(+$('taxPercent').value||0)/100;$('subtotal').textContent=money(s);$('tax').textContent=money(tax);$('grandTotal').textContent=money(s+tax)}
async function saveInvoice(){let data={invoiceNo:$('invoiceNo').value,date:$('invoiceDate').value,customerId:$('customerSelect').value,customer:$('customer').value.trim(),phone:$('phone').value.trim(),email:$('email').value.trim(),address:$('address').value.trim(),taxPercent:+$('taxPercent').value||0,status:$('status').value,paymentMethod:$('paymentMethod').value,notes:$('notes').value.trim(),items:getItems()};if(!data.customer)return toast('Nama customer belum diisi.',true);if(!data.items.length)return toast('Minimal ada 1 item.',true);try{$('saveBtn').disabled=true;let r=await api('saveInvoice',{data});closeModal('formModal');toast(`Invoice ${r.invoiceNo} berhasil disimpan.`);await loadData();previewInvoice(encodeURIComponent(r.invoiceNo))}catch(e){toast(e.message,true)}finally{$('saveBtn').disabled=false}}
async function previewInvoice(enc){try{let inv=await api('getInvoice',{invoiceNo:decodeURIComponent(enc)});$('printArea').innerHTML=buildInvoiceHTML(inv);openModal('previewModal')}catch(e){toast(e.message,true)}}
function buildInvoiceHTML(i){let s=APP.settings,rows=(i.items||[]).map(x=>`<tr><td>${x.no}</td><td>${escapeHtml(x.description)}</td><td style="text-align:center">${x.qty}</td><td style="text-align:right">${money(x.price)}</td><td style="text-align:right">${money(x.total)}</td></tr>`).join('');return `<div class="invoice"><div class="invoice-top"><div><div class="company">${escapeHtml(s['Nama Perusahaan']||'NAMA PERUSAHAAN')}</div><div class="company-sub">${escapeHtml(s['Alamat Perusahaan']||'')}</div></div><div style="text-align:right"><div class="invoice-title">INVOICE</div><div style="font-size:10px">${escapeHtml(s['Website']||'')}</div></div></div><div class="invoice-line"></div><div class="invoice-info"><div><div>Invoice To :</div><div class="customer-name">${escapeHtml(i.customer)}</div><div>${escapeHtml(i.phone||'')}</div><div>${escapeHtml(i.email||'')}</div><div>${escapeHtml(i.address||'')}</div></div><div style="text-align:right"><strong>Invoice No : ${escapeHtml(i.invoiceNo)}</strong><br>${escapeHtml(i.date)}</div></div><table class="invoice-table"><thead><tr><th>NO</th><th>DESCRIPTION</th><th>QTY</th><th>PRICE</th><th>TOTAL</th></tr></thead><tbody>${rows}</tbody></table><div class="invoice-bottom"><div class="payment"><div class="payment-title">PAYMENT METHOD :</div><br><strong>${escapeHtml(i.paymentMethod||'')}</strong><br><br>Bank Name : ${escapeHtml(s['Nama Bank']||'')}<br>Account Number : ${escapeHtml(s['No. Rekening']||'')}<br>Account Name : ${escapeHtml(s['Atas Nama']||'')}</div><div class="summary"><div class="summary-row"><span>Sub Total :</span><span>${money(i.subtotal)}</span></div><div class="summary-row"><span>Tax ${i.taxPercent}% :</span><span>${money(i.tax)}</span></div><div class="summary-grand"><div class="summary-row"><span>GRAND TOTAL :</span><span>${money(i.grandTotal)}</span></div></div></div></div><div class="terms"><strong>Terms and Conditions :</strong><br><br>${escapeHtml(s['Syarat Pembayaran']||'')}</div><div class="footer"><span>${escapeHtml(s['Telepon']||'')}</span><span>${escapeHtml(s['Email']||'')}</span><span>${escapeHtml(s['Alamat Perusahaan']||'')}</span></div></div>`}
function openModal(id){$(id).classList.add('show')}function closeModal(id){$(id).classList.remove('show')}function money(v){return'Rp '+Number(v||0).toLocaleString('id-ID')}
function toast(m,e=false){let x=$('toast');x.textContent=m;x.style.background=e?'#b42318':'#1f2937';x.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>x.classList.remove('show'),2800)}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function escapeAttr(v){return escapeHtml(v)}
